Algoritmo "pagamento"
//  
//  

Var

   nome : caractere
   val : real
   hr : inteiro
   pag : real

Inicio

   nome <- "João Silva"
   val <- 17
   hr <- 8
   
   pag <- val*hr
   
   escreval ("Nome: ",nome)
   escreval ("Valor por hora: ",val:1:2)
   escreval ("Horas trabalhadas por ",nome,":", hr)
     escreval
   escreval ("O pagamento para ", nome ," deve ser = ", pag:1:2)


Fimalgoritmo
