Algoritmo "TempoLol"
//  
//  


Var

nick : caractere
min : inteiro
hrs : real
dia : real
Inicio

     nick <- "BananaEater"
     min <- 5383
     hrs <- min/60
     dia <- min/1440

 escreval ("Insira um Nick: ",nick)
    escreval
 escreval ("Voce ja gastou:")
    escreval
 escreval (" ",min," minutos ou")
    escreval
 escreval (" ",hrs:9:3," horas ou")
    escreval
 escreval (" ",dia:5:1, " dias no LoL!")

Fimalgoritmo