Algoritmo "troco"
//  
//  

var

    prod : real
    pre : real
    qtd : inteiro
    
    rec : real
    trc : real


Inicio

   prod <- 8
   qtd <- 2
   rec <- 20

   pre <- prod*qtd
   
   trc <- rec-pre



   escreval ("Preço unitário do produto: ",prod:1:2)
   escreval ("Quantidade comprada: ",qtd)
   escreval ("Dinheiro recebido: ",rec:1:2)
     escreval
   escreval ("TROCO = ",trc:1:2)

Fimalgoritmo