Algoritmo "crescente"
//this code tells when numbers are bigger than others
//the code ends if you put two of the same number

Var

  x, y : inteiro

Inicio

  escreval ("Digite dois numeros: ")
  leia (x)
  leia (y)
  
  enquanto (x <> Y) faca
  
     se (x > y) entao
        escreval ("DECRESCENTE!")
     senao
        escreval ("CRESCENTE!")
     fimse
     
     escreval ("Digite outros dois numeros: ")
     leia (x)
     leia (y)

  fimenquanto
Fimalgoritmo
