Algoritmo "expressao 'e'(teste)"
//code made to test the logic expression "E"
//E sugest that all conditions in a sentence are true
//"E" in portugol is the equivalent of "and" of other languages
Var

   x: inteiro
   
   a,b,c,d: logico

Inicio

  x <- 5
  
  a <- (x <= 20) e (x = 10)
  
  b <- (x > 0) e (x <> 3)
  
  c <- (x <= 20) e (x = 7) e (x <> 6)
  
  d <- (x^2 = 25) e (x\2 = 2) e (x + 1 + 4 = 10)

Fimalgoritmo
